accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),

    path('<username>/', views.ProfileDashboard, name='dashboard'),
    # path('<username>/edit_student_profile', views.EditStudentProfileView, name='edit_student_profile'),

]

blog/urls.py
from django.urls import path,include
from . import views


app_name = 'blog'


urlpatterns = [
    path('', views.blog, name='blog'),
    path('<postid>/', views.detail, name='detail'),
    path('<postid>/<commentid>/', views.CommentDelete, name='comment_delete')
]

cncweb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, \
    PasswordResetConfirmView, PasswordChangeView, PasswordChangeDoneView
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from blog.models import Post
from events.models import Event
from events.models import Event
from accounts.models import UserProfile, FacultyProfile
import blog.views
from rest_framework.authtoken import views
from blog.sitemaps import StaticViewSitemap
from core import views as coreviews

sitemaps = {
    'static': StaticViewSitemap,

    'blog': GenericSitemap({
        'queryset': Post.objects.all(),
        'date_field': 'date',
    }, priority=0.7),

    'event': GenericSitemap({
        'queryset': Event.objects.all(),
        'date_field': 'date',
    }, priority=0.8),

    'students': GenericSitemap({
        'queryset': UserProfile.objects.all(),
    }, priority=0.5),

    'teachers': GenericSitemap({
        'queryset': FacultyProfile.objects.all(),
    }, priority=0.6),

}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),

    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('change_password/', PasswordChangeView.as_view(), name='change_password'),
    path('password_change_done/', PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('events/', include('events.urls', namespace='events')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

    path('api-token-auth/', views.obtain_auth_token),
    path('api-auth/', include('rest_framework.urls')),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots\.txt', include('robots.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

]

handler404 = 'core.views.handler404'
handler500 = 'core.views.handler500'
handler403 = 'core.views.handler403'
handler400 = 'core.views.handler400'


# if settings.DEBUG==True:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

events/urls.py
from django.urls import path
from . import views


app_name = 'events'


urlpatterns = [
    path('', views.EventsList, name='events_list'),
    path('<int:eventid>/', views.EventDetail, name='events_detail'),
    path('certi', views.Getpdf, name='certi'),
    path('<username>/<eventid>/', views.Getpdf, name='certificate'),
    path('<eventid>/register', views.RegisterForEvent, name='register_for_event'),
    path('<eventid>/unregister', views.UnregisterForEvent, name='unregister_for_event'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

courses = (
    ('BTECH', 'Btech'),
    ('MTECH', 'Mtech'),
    ('BCA', 'BCA'),
    ('MCA', 'MCA'),
    ('BSC', 'Bsc'),
    ('MSC', 'Msc'),
    ('MBA', 'MBA'),
    ('BBA', 'BBA'),
)

branch = (
    ('CE', 'CE'),
    ('IT', 'IT'),
    ('ECE', 'ECE'),
    ('ECS', 'ECS'),
    ('EIC', 'EIC'),
    ('EL', 'EL'),
    ('MECH', 'MECH'),
    ('CIVIL','CIVIL'),
    ('Mathematics', 'Mathematics'),
    ('Chemistry','Chemistry'),
    ('Physics','Physics'),
    ('Animation','Animation'),
    ('Others','Others'),

)

faculty_position = (
    ('Head', '1-Head'),
    ('Member', '2-Member'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    pic = models.ImageField(default='student pics/default_user.png', upload_to='student pics', blank=True, null=True)
    roll_no = models.BigIntegerField(unique=True)
    course = models.CharField(choices=courses, max_length=50)
    branch = models.CharField(choices=branch, max_length=50)
    icard = models.ImageField(upload_to='icard', blank=True, null=True)
    phoneno = models.BigIntegerField(default=None)

    def __str__(self):
        return str(self.user) + ' ' + str(self.roll_no)
    
    def get_absolute_url(self):
        return reverse('accounts:dashboard', args=[str(self.user.username)])
    
    class Meta:
        ordering = ['-roll_no', 'branch', 'course']


class FacultyProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pic = models.ImageField(default=None, upload_to='faculty pics', blank=True, null=True)
    department = models.CharField(max_length=20)
    position = models.CharField(choices=faculty_position, max_length=20)

    def __str__(self):
        return str(self.user)
    
    def get_absolute_url(self):
        return reverse('accounts:dashboard', args=[str(self.user.username)])
    
    class Meta:
        ordering = ['position']

events/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField


class Event(models.Model):
    event_name = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    certi_description = RichTextUploadingField(blank=True, null=True)
    content = RichTextUploadingField(blank=True, null=True)
    date = models.DateTimeField(blank=True, null=True)
    venue = models.CharField(max_length=100, default=None, blank=True, null=True)
    pic1 = models.ImageField(default=None, upload_to='event pics')
    pic2 = models.ImageField(default=None, upload_to='event pics', blank=True, null=True)
    pic3 = models.ImageField(default=None, upload_to='event pics', blank=True, null=True)
    pic4 = models.ImageField(default=None, upload_to='event pics', blank=True, null=True)
    pic5 = models.ImageField(default=None, upload_to='event pics', blank=True, null=True)
    pic6 = models.ImageField(default=None, upload_to='event pics', blank=True, null=True)
    pic7 = models.ImageField(default=None, upload_to='event pics', blank=True, null=True)
    pic8 = models.ImageField(default=None, upload_to='event pics', blank=True, null=True)
    pic9 = models.ImageField(default=None, upload_to='event pics', blank=True, null=True)
    pic10 = models.ImageField(default=None, upload_to='event pics', blank=True, null=True)
    pic11 = models.ImageField(default=None, upload_to='event pics', blank=True, null=True) ##for home only
    status = models.CharField(default=True, choices=(('True', 'Upcoming'), ('False', 'Happened')), max_length=10)

    def __str__(self):
        return self.event_name

    def get_absolute_url(self):
        return reverse('events:events_detail', args=[str(self.pk)])

    class Meta:
        ordering = ['-date']


class Registration(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='registrations')
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    attended = models.CharField(choices=(('A', 'Attended'), ('NA', 'Not Attended')), max_length=10, default='NA')

    def __str__(self):
        return self.event.event_name + self.user.username

    def is_user_registered_for_event(self, user, event):
        if self.objects.get(user=user, event=event):
            return True
        else:
            return False

    class Meta:
        ordering = ['-date']


class Institute(models.Model):
    institute = models.CharField(max_length=100)
    previous_events = RichTextUploadingField(blank=True, null=True)
    contact_person = models.CharField(max_length=1000, blank=True, null=True)
    contact_person_phone_number = models.BigIntegerField(blank=True, null=True)
    email = models.EmailField(max_length=100, default=None, blank=True, null=True)

    def __str__(self):
        return self.institute

    class Meta:
        ordering = ['institute']

accounts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from .models import UserProfile


course = (
    ('BTECH', 'Btech'),
    ('MTECH', 'Mtech'),
    ('BCA', 'BCA'),
    ('MCA', 'MCA'),
    ('BSC', 'Bsc'),
    ('MSC', 'Msc'),
    ('MBA', 'MBA'),
)

branch = (
    ('CE', 'CE'),
    ('IT', 'IT'),
    ('ECE', 'ECE'),
    ('ECS', 'ECS'),
    ('EIC', 'EIC'),
    ('EL', 'EL'),
    ('MECH', 'MECH'),
    ('CIVIL','CIVIL'),
    ('Mathematics', 'Mathematics'),
    ('Chemistry','Chemistry'),
    ('Physics','Physics'),

)


class UserRegistrationForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    first_name = forms.CharField(label='First Name', max_length=50)
    last_name = forms.CharField(label='Last Name', max_length=50)
    email = forms.EmailField(label='Email ID')

    password1 = forms.CharField(label='Password', min_length=6,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Confirm Password', min_length=6,)
    roll_no = forms.IntegerField(label='Roll No.', min_value=10000000000, max_value=100000000000)
    course = forms.ChoiceField(label='Course', choices=course)
    branch = forms.ChoiceField(label='Branch', choices=branch)
    phoneno = forms.IntegerField(label='Phone No.', min_value=6000000000, max_value=9999999999)
    icard = forms.ImageField(label='I-card Front', allow_empty_file=True, required=False)

    def clean(self):
        cleaned_data = super().clean()
        p1 = cleaned_data.get('password1')
        p2 = cleaned_data.get('password2')
        if p1 and p2:
            if p1 != p2:
                raise ValidationError('Password Mismatch')

    def clean_email(self):
        email = self.cleaned_data['email']
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise ValidationError('Email is already registered.')
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        qs = User.objects.filter(username=username.lower())
        spaces = username.count(' ')
        if qs.exists():
            raise ValidationError('Username is already registered.')
        elif spaces > 0:
            raise ValidationError('Spaces not allowed in Username')
        return username

    def clean_roll_no(self):
        roll_no = self.cleaned_data['roll_no']
        qs = UserProfile.objects.filter(roll_no=roll_no)
        if qs.exists():
            raise ValidationError('Roll Number is already registered.')
        return roll_no


class UserLogin(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(label='Password', min_length=6,
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class EditUser(forms.ModelForm):
    username = forms.CharField(label='Username',max_length=100)
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['email', 'username']

    # def clean_password1(self):
    #     password = self.cleaned_data['password1']
    #     if not self.user.check_password(password):
    #         raise ValidationError('Invalid password')
    #     return password

    # def clean_username(self):
    #     username = self.cleaned_data['username']
    #     qs = User.objects.filter(username=username)
    #     spaces = username.count(' ')
    #     if u
    #     elif qs.exists():
    #         raise ValidationError('Username is already registered.')
    #     elif spaces > 0:
    #         raise ValidationError('Spaces not allowed in Username')
    #     return username

    # def clean_email(self):
    #     email = self.cleaned_data['email']
    #     qs = User.objects.filter(email=email)
    #     if qs.exists():
    #         raise ValidationError('Email is already registered.')
    #     return email


class EditStudentProfile(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['pic', 'phoneno']


class ChangePassword(forms.ModelForm):
    current_password = forms.CharField(label='Current Password',min_length=6,
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password = forms.CharField(label='New Password',min_length=6,
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    confirm_new_password = forms.CharField(label='Confirm New Password',min_length=6,
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['current_password', 'new_password', 'confirm_new_password']

accounts/templates/accounts/login1.html
{% extends 'base.html' %}
{% load static %}
{% block static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Login | Career and Counseling Cell | JC Bose University</title>
    <meta name="title" content="Login | Career and Counseling Cell | JC Bose University">
    <meta name="description" content="Career and Counseling helps student to achieve excellence in their respective fields and oraganizes seminars in JC BOSE University, YMCA, Faridabad">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://www.cncjcbust.tech/login/">
    <meta property="og:title" content="Login | Career and Counseling Cell | JC Bose University">
    <meta property="og:description" content="Career and Counseling helps student to achieve excellence in their respective fields and oraganizes seminars in JC BOSE University, YMCA, Faridabad">
    <meta property="og:image" content="{% static 'img/logo.png' %}">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="https://www.cncjcbust.tech/login/">
    <meta property="twitter:title" content="Login | Career and Counseling Cell | JC Bose University">
    <meta property="twitter:description" content="Career and Counseling helps student to achieve excellence in their respective fields and oraganizes seminars in JC BOSE University, YMCA, Faridabad">
    <meta property="twitter:image" content="{% static 'img/logo.png' %}">

    {% endblock %}

{% block content %}
<br>
<br>
<br>
<div style="background: rgb(2,0,36);
background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(255,10,151,1) 0%, rgba(255,0,0,1) 100%); padding: 50px;">
<div class="card wow slideInUp container mt-5 border-white border rounded shadow-lg" style="display: flex; justify-content: center;">
    <div class="mt-3" align="center">
        <img src="{% static 'img/loginlogo.png' %}" height="80" width="80" class="rounded">
    </div>
    <div class="container">
        <div class="form">
            <h2 class="mb-4 font-weight-light mt-3"><center>Login</center></h2>
          <form class="mt-3" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
            <div class="row">
              <div class="col-lg-12">
                <div class="form-group" align="center">
                  <input class="form-control" name="username" placeholder="Username" style="border-radius: 30px;">
                </div>
              </div>

              <div class="col-lg-12" align="center">
                <div class="form-group">
                  <input class="form-control" type="password" name="password" placeholder="Password" style="border-radius: 30px;">
                </div>
              </div>

              <div class="col-lg-12" align="center">
                <button style="border-radius: 30px; background: rgb(2,0,36);
background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(255,10,151,1) 0%, rgba(255,0,0,1) 100%);" type="submit" value="submit" class="btn  btn-md btn-block text-white border-0"><span> Login </span></button>
                <!--  -->
              </div>
            </div>
          </form>
            <div class="col mt-4" align="center">
              Don't have an account? <a href="{% url 'accounts:register' %}" class="text-danger">Sign Up</a>
            </div>
            <div class="col mt-1" align="center">
              Forgot Password? <a href="/password_reset" class="text-danger">Reset</a>
            </div>

          </div>
    </div>
</div>
</div>




    {% endblock %}
    {% block scripts %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% endblock %}

accounts/templates/accounts/profile card.html
<div class="container body">
</div>
    <center>
    <div class="card container profilebody border-white border rounded shadow-lg img-fluid" style="height: auto; margin-top: -150px;">
            <div class="wow slideInUp profile">
                <div class="profilephoto" style="margin-top: 30px;">
                    {% if user_instance.userprofile.pic %}
                    <a href="#">
                        <img src="{{user_instance.userprofile.pic.url}}" height="100" width="100" class="rounded-circle">
                    </a>
                    {% endif %}
                </div>
                <div class="profiledetails">
                    <br>
                    <h2>{{user_instance.first_name|capfirst}} {{ user_instance.last_name|capfirst }}</h2>
                    <br>
                    <!-- and role or location -->
                    <h4>{{profile.roll_no}}</h4><br>
                    <h5><p>{{profile.course}} - {{ profile.branch }}</p></h5>


                    {% if request.user == user_instance %}
                    <div style="padding-bottom: 20px">
                     <hr>

                        <button type="button" class="btn btn-info"><a href="{% url 'accounts:edit_student_profile' user_instance.username %}">Edit Profile</a></button>
                        <button type="button" class="btn btn-danger"><a href="{% url 'change_password' %}">Password</a></button>
                    </div>
                    {% endif %}
                </div>

            </div>
    </div>
    </center>
    <br>
{% if user_instance.registration_set.exists %}

    <div class="wow slideInUp container certibody">
        <div style="text-align: center">
            <h2 class="text-white img-fluid">
                CERTIFICATES
            </h2>
            <hr style="background-color: ghostwhite">
            <br><br>




            <div class="row user-list">
                {% for registration in certificates %}
                {% if registration.attended == 'A'%}
                    <div class="col-md-3 col-sm-6 item">
                        <div class="card border-white border rounded shadow-lg" data-bs-hover-animate="pulse" style="width: auto; height: 15rem;">
                            <div class="card-body">
                                <h4 class="card-title" style="margin-top: 5px;"><strong>{{ registration.event.event_name|capfirst|truncatechars:40 }}</strong></h4>
                                <h6 class="text-muted card-subtitle mb-2" style="margin-top: 0px;">{{ registration.event.date }}</h6>

                                <p class="card-text" style="width: 180px;margin-top: 15px;margin-bottom: 20px;">{{ registration.event.description|capfirst|truncatechars:40 }}</p>

                                <div class="btn-group" role="group">
                                    <button class="btn bg-danger" type="button" ><a href="{% url 'events:certificate' user_instance.username registration.event.id %}">Certificate</a></button>
                                    <br>
                                    <button class="btn bg-info" type="button"><a href="{% url 'events:events_detail' registration.event.id %}">Detail</a></button>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
                {% endfor %}
            </div>

                </div>
        {% endif %}
        </div>
    </div>


<style>
    .body{
        margin-top: 25px;
        background-color: white;
        padding-top: 150px;
    }
    .row .item{
        margin-bottom: 20px;
    }
    a{
        text-decoration: none;
        color: white;
    }
    a:hover{
        text-decoration: none;
        color: white;
    }
    .editoptions{
        text-align: center;
    }

</style>

accounts/templates/accounts/register1.html
{% extends 'base.html' %}
{% load static %}
{% block static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Register | Career and Counseling Cell | JC Bose UST</title>
    <meta name="title" content="Register | Career and Counseling Cell | JC Bose UST">
    <meta name="description" content="Career and Counseling helps student to achieve excellence in their respective fields and oraganizes seminars in JC BOSE University, YMCA, Faridabad">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://cncjcbust.tech/about/">
    <meta property="og:title" content="Register | Career and Counseling Cell | JC Bose UST">
    <meta property="og:description" content="Career and Counseling helps student to achieve excellence in their respective fields and oraganizes seminars in JC BOSE University, YMCA, Faridabad">
    <meta property="og:image" content="{% static 'img/logo.png' %}">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="https://cncjcbust.tech/about/">
    <meta property="twitter:title" content="Register | Career and Counseling Cell | JC Bose UST">
    <meta property="twitter:description" content="Career and Counseling helps student to achieve excellence in their respective fields and oraganizes seminars in JC BOSE University, YMCA, Faridabad">
    <meta property="twitter:image" content="{% static 'img/logo.png' %}">

{% endblock %}



{% block content %}
<br>
<br>
<br>
<div style="background: rgb(2,0,36);
background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(255,10,151,1) 0%, rgba(255,0,0,1) 100%); padding: 50px;">
  <div class="card wow slideInUp container mt-5 border-white border rounded shadow-lg" style="width: 95%; text-align: center;">
    <div class="mt-3" align="center">
        <img src="{% static 'img/loginlogo.png' %}" height="80" width="80" class="rounded">
    </div>
    <div class="container">
        <div class="form">
            <h2 class="mb-4 font-weight-light mt-3"><center>Register</center></h2>
          <form class="mt-3" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
            <div class="row">
              <div class="col-lg-12">
                <div class="form-group" align="center">
                  <input style="border-radius: 30px;" class="form-control" name="username" required id="id_username" type="Username" maxlength="50" placeholder="Username">
                </div>
              </div>

              <div class="col-lg-12">
                <div class="form-group" align="center">
                  <input style="border-radius: 30px;" class="form-control" name="first_name" required id="id_first_name" maxlength="50" type="text" placeholder="First Name">
                </div>
              </div>

              <div class="col-lg-12">
                <div class="form-group" align="center">
                  <input style="border-radius: 30px;" class="form-control" name="last_name" required id="id_last_name" maxlength="50" type="text" placeholder="Last Name">
                </div>
              </div>

              <div class="col-lg-12">
                <div class="form-group" align="center">
                  <input style="border-radius: 30px;" class="form-control" name="roll_no" required id="id_roll_no" type="Number" placeholder="Roll Number" max="100000000000" min="10000000000">
                </div>
              </div>

              <div class="col-lg-12">
                <div class="form-group" align="center">
                  <input style="border-radius: 30px;" class="form-control" name="email" required id="id_email" type="email" placeholder="Email Address">
                </div>
              </div>

              <div class="col-lg-12">
                <div class="form-group" align="center">
                  <input style="border-radius: 30px;" class="form-control" name="phoneno" required id="id_phoneno" type="Number" placeholder="Primary Phone Number" max="9999999999" min="6000000000">
                </div>
              </div>

              <div class="col-lg-6">
                <div class="form-group">
                  <label for="id_course">Course:</label>
                  <select style="border-radius: 30px;" class="form-control" name="course" id="id_course">
                    <option value="BTECH">B.Tech</option>
                    <option value="MTECH">M.Tech</option>
                    <option value="BCA">BCA</option>
                    <option value="MCA">MCA</option>
                    <option value="BSC">B.Sc</option>
                    <option value="MSC">M.Sc</option>
                    <option value="MBA">MBA</option>
                    <option value="BBA">BBA</option>
                </select>
                </div>
              </div>

              <div class="col-lg-6">
                <div class="form-group">
                  <label for="id_branch">Branch:</label>
                  <select style="border-radius: 30px;" class="form-control" name="branch" id="id_branch">
                    <option value="CE">CE</option>
                    <option value="IT">IT</option>
                    <option value="ECE">ECE</option>
                    <option value="ECS">ECS</option>
                    <option value="EIC">EIC</option>
                    <option value="EL">EL</option>
                    <option value="MECH">MECH</option>
                    <option value="CIVIL">CIVIL</option>
                    <option value="Mathematics">Mathematics</option>
                    <option value="Chemistry">Chemistry</option>
                    <option value="Physics">Physics</option>
                    <option value="Animation">Animation</option>
                    <option value="Others">Others</option>
                </select>
                </div>
              </div>

              <div class="col-lg-12">
                <div class="form-group">
                  <input style="border-radius: 30px;" class="form-control" name="password1" minlength="6" required id="id_password1" type="password" placeholder="Choose Password">
                </div>
              </div>

              <div class="col-lg-12">
                <div class="form-group">
                  <input style="border-radius: 30px;" class="form-control" name="password2" minlength="6" required id="id_password2" type="password" placeholder="Confirm Password">
                </div>
              </div>

              <div class="col-lg-12">
                <div class="form-group">
                  <label for="id_icard">I-card Front:</label><input type="file" name="icard" accept="image/*" id="id_icard">
                </div>
              </div>

              <div class="col-lg-12" align="center">
                <button style="border-radius: 30px; background: rgb(2,0,36);
background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(255,10,151,1) 0%, rgba(255,0,0,1) 100%);" type="submit" value="submit" class="btn  btn-md btn-block text-white border-0"><span> Create Account </span></button>

              </div>
            </div>
          </form>
            <div class="col mt-4" align="center">
              Already have an account? <a href="{% url 'accounts:login' %}" class="text-danger">Log In</a>
            </div>
          </div>
    </div>
</div>
</div>
    {% endblock %}
    {% block scripts %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% endblock %}