accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),

    path('<username>/', views.ProfileDashboard, name='dashboard'),
    # path('<username>/edit_student_profile', views.EditStudentProfileView, name='edit_student_profile'),

]

blog/urls.py
from django.urls import path,include
from . import views


app_name = 'blog'


urlpatterns = [
    path('', views.blog, name='blog'),
    path('<postid>/', views.detail, name='detail'),
    path('<postid>/<commentid>/', views.CommentDelete, name='comment_delete')
]

cncweb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, \
    PasswordResetConfirmView, PasswordChangeView, PasswordChangeDoneView
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from blog.models import Post
from events.models import Event
from events.models import Event
from accounts.models import UserProfile, FacultyProfile
import blog.views
from rest_framework.authtoken import views
from blog.sitemaps import StaticViewSitemap
from core import views as coreviews

sitemaps = {
    'static': StaticViewSitemap,

    'blog': GenericSitemap({
        'queryset': Post.objects.all(),
        'date_field': 'date',
    }, priority=0.7),

    'event': GenericSitemap({
        'queryset': Event.objects.all(),
        'date_field': 'date',
    }, priority=0.8),

    'students': GenericSitemap({
        'queryset': UserProfile.objects.all(),
    }, priority=0.5),

    'teachers': GenericSitemap({
        'queryset': FacultyProfile.objects.all(),
    }, priority=0.6),

}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),

    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('change_password/', PasswordChangeView.as_view(), name='change_password'),
    path('password_change_done/', PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('events/', include('events.urls', namespace='events')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

    path('api-token-auth/', views.obtain_auth_token),
    path('api-auth/', include('rest_framework.urls')),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots\.txt', include('robots.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

]

handler404 = 'core.views.handler404'
handler500 = 'core.views.handler500'
handler403 = 'core.views.handler403'
handler400 = 'core.views.handler400'


# if settings.DEBUG==True:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import home, about, contact_us, UserViewSet, UserProfileViewSet, BlogViewSet, EventViewSet, auditions, reports
from . import views as coreviews
from rest_framework.routers import DefaultRouter
app_name = 'core'

router = DefaultRouter()
router.register('users', UserViewSet, basename='user')
router.register('userprofiles', UserProfileViewSet, basename='userprofile')
router.register('blogs', BlogViewSet, basename='blog')
router.register('events', EventViewSet, basename='event')


urlpatterns = [
    path('', home, name='home'),
    # path('auditions/', auditions, name='auditions'),

    path('analyst/', coreviews.analyst),
    path('avtar/', coreviews.avtar),
    path('current-affairs/', coreviews.currentaffairs),
    path('dribble/', coreviews.dribble),
    path('musketeer/', coreviews.musketeer),
    path('rabindranath/', coreviews.rabindernath),
    path('silent-past/', coreviews.silentpast),
    path('snapes-in-plane/', coreviews.snapes_in_plane),
    path('the-rohan-chaudhary-show/', coreviews.therohanchaudharyshow),
    path('treasurer/', coreviews.treasurer),


    path('about/', about, name='about'),
    path('contact/', contact_us, name='contact'),
    path('reports/', reports, name='reports'),
    
    path('api/', include(router.urls)),

]

events/urls.py
from django.urls import path
from . import views


app_name = 'events'


urlpatterns = [
    path('', views.EventsList, name='events_list'),
    path('<int:eventid>/', views.EventDetail, name='events_detail'),
    path('certi', views.Getpdf, name='certi'),
    path('<username>/<eventid>/', views.Getpdf, name='certificate'),
    path('<eventid>/register', views.RegisterForEvent, name='register_for_event'),
    path('<eventid>/unregister', views.UnregisterForEvent, name='unregister_for_event'),

]

templates/base.html
<!DOCTYPE html>
<html  lang="en" dir="ltr">
{% load static %}
<head>


    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta charset="utf-8">
    <meta name="MobileOptimized" content="true">
    <meta name="HandheldFriendly" content="true">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="author" content="Career and Counseling Cell">
    <meta name="keywords" content="Career and Counseling Cell, Career and Counselling Cell, YMCA university, Ymca UST, JC BOSE UST, JC Bose University, Career and Counselling Cell JC Bose university, CNC JC Bose University, CNC YMCA University">
    <meta name="google-site-verification" content="8j3kLtd9tSf2Lg6xz6tFVYVsiarTl2gkKGvCjqscmw8" />

    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
    <link href="https://fonts.googleapis.com/css?family=ZCOOL+XiaoWei&display=swap" rel="stylesheet">
    {% block title %}
    {% endblock %}
    {% load static %}
    {% block static %}
    {% endblock %}

    <!-- Common OG Meta Tags -->
    <meta name="og:site_name" content="Career and Counseling Cell"/>
    <meta name="fb:page_id" content="687720628037717" />
    <meta name="og:email" content="cccell@jcboseust-ymca.ac.in"/>
    <meta name="og:phone_number" content="0129 231 0126"/>

    <meta name="og:latitude" content="28.366785"/>
    <meta name="og:longitude" content="77.316485"/>

    <meta name="og:street-address" content="Career and Counselling Cell"/>
    <meta name="og:locality" content="JC BOSE University, YMCA"/>
    <meta name="og:region" content="Faridabad, Haryana"/>
    <meta name="og:postal-code" content="121006"/>
    <meta name="og:country-name" content="INDIA"/>




    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=ABeeZee">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Aguafina+Script">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Akronim">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/Footer-Basic.css' %}">
    <link rel="stylesheet" href="{% static 'css/Social-Menu-Sticky.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
    <style>
        *{
            font-family: 'ZCOOL XiaoWei', serif;
            font-size: 18px;

        }
    </style>
</head>





<body> <!-- style="background-image: url(&quot;none&quot;);" -->







{% include 'navbar.html' %}
  <!-- Messages -->
  {% if messages %}
  <div class="fixed-top">
        {% for message in messages %}
            {% if message.tags == 'error' %}
            <div class="alert alert-danger alert-dismissible fade show " role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% else %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show " role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
    {% endfor %}
  </div>
{% endif %}
    <!-- EndMessages -->


<div id="fixed-social">
    <div><a class="fixed-facebook" href="https://www.facebook.com/cccymcaust/" target="_blank"><i class="fa fa-facebook"></i><span>&nbsp;Facebook</span></a></div>
    <div><a class="fixed-instagram" href="https://www.instagram.com/career_counselling_cell_ymca/" target="_blank"><i class="fa fa-instagram"></i><span>&nbsp;Instagram</span></a></div>
    <div><a class="fixed-youtube" href="https://www.youtube.com/channel/UCuiPk4pocoSo0Dr6QjhoSaQ" target="_blank"><i class="fa fa-youtube"></i><span>&nbsp;Youtube</span></a></div>
</div>



{% block content %}
{% endblock %}


{% include 'footer.html' %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js">

    </script>
    <script>
        new WOW().init();
    </script>

    {% block scripts %}
    {% endblock %}
</body>

</html>

templates/footer.html
<div class="footer-basic wow fadeInUp">
    <footer>
        <div class="social">
            <a href="https://www.instagram.com/career_counselling_cell_ymca/"><i class="icon ion-social-instagram"></i></a>
            <a href="https://www.youtube.com/channel/UCuiPk4pocoSo0Dr6QjhoSaQ"><i class="icon ion-social-youtube"></i></a>
{#            <a href="#"><i class="icon ion-social-snapchat"></i></a>#}
{#            <a href="#"><i class="icon ion-social-twitter"></i></a>#}
            <a href="https://www.facebook.com/cccymcaust/"><i class="icon ion-social-facebook"></i></a></div>


        <ul class="list-inline">
            <li class="list-inline-item"><a href="{% url 'core:home' %}">Home</a></li>
            <li class="list-inline-item"><a href="{% url 'core:about' %}">About</a></li>
            <li class="list-inline-item"><a href="{% url 'events:events_list' %}">Events</a></li>
            <li class="list-inline-item"><a href="{% url 'blog:blog' %}">Blog</a></li>
            <li class="list-inline-item"><a href="{% url 'core:contact' %}">Contact Us</a></li>
        </ul>
        <p class="copyright">Career and Counselling Cell © 2020</p>
    </footer>
</div>

templates/home.html
{% extends 'base.html'%}
{% load static %}
{% block static %}
    <!-- Primary Meta Tags -->
    <title>Career and Counseling Cell | JC Bose University Faridabad</title>
    <meta name="title" content="Career and Counseling Cell, JC Bose University Faridabad">
    <meta name="description" content="Career and Counseling helps student to achieve excellence in their respective fields and oraganizes seminars in JC BOSE University, YMCA, Faridabad">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://www.cncjcbust.tech/">
    <meta property="og:title" content="Career and Counseling Cell, JC Bose University Faridabad">
    <meta property="og:description" content="Career and Counseling helps student to achieve excellence in their respective fields and oraganizes seminars in JC BOSE University, YMCA, Faridabad">
    <meta property="og:image" content="https://www.cncjcbust.tech/static/img/logo.227277181681.png">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="https://www.cncjcbust.tech/">
    <meta property="twitter:title" content="Career and Counseling Cell, JC Bose University Faridabad">
    <meta property="twitter:description" content="Career and Counseling helps student to achieve excellence in their respective fields and oraganizes seminars in JC BOSE University, YMCA, Faridabad">
    <meta property="twitter:image" content="https://www.cncjcbust.tech/static/img/logo.227277181681.png">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/pace.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/themes/red/pace-theme-flash.min.css">


{% endblock %}



{% block content %}
    <br>
    <br>
    <br>
    <br>


    {% include 'home_carousel.html' %}
    {% include 'upcoming_events_card.html' %}
    {% include 'core/message.html' %}
    {% include 'core/about_college.html' %}


{% endblock %}








{% block scripts %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>


{% endblock %}

templates/home_carousel.html
{% load static %}
{% if slideshows %}

    <section id="carousel">
        <div class="carousel slide" data-ride="carousel" id="carousel-1">
            <div class="carousel-inner" role="listbox">

                {% for slide in slideshows %}
                    {% if forloop.counter == 1 %}
                        <div class="carousel-item active intro-item bg-image">
                            <div class="jumbotron pulse animated hero-nature carousel-hero" style="background-image: url('{{slide.image.url}}'); height: 60vh; background-size: cover; background-repeat: no-repeat">
                                <h1 class="hero-title">{{ slide.title|title }}</h1>
                                <p class="hero-subtitle">{{ slide.description }}</p>
                                <p><a class="btn btn-primary hero-button plat" role="button" href="{{ slide.url }}">Know more</a></p>
                            </div>
                        </div>

                    {% else %}
                        <div class="carousel-item intro-item bg-image">
                            <div class="jumbotron pulse animated hero-nature carousel-hero" style="background-image: url('{{slide.image.url}}'); height: 60vh; background-size: cover; background-repeat: no-repeat">
                                {% if slide.title %}
                                <h1 class="hero-title">{{ slide.title }}</h1>
                                {% endif %}
                                {% if slide.description %}
                                <p class="hero-subtitle">{{ slide.description }}</p>
                                {% endif %}
                                <p><a class="btn btn-primary hero-button plat" role="button" href="{{ slide.url }}">Know more</a></p>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}


            </div>
            <div><a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev"><i class="fa fa-chevron-left"></i><span class="sr-only">Previous</span></a><a class="carousel-control-next" href="#carousel-1" role="button" data-slide="next"><i class="fa fa-chevron-right"></i><span class="sr-only">Next</span></a></div>

            <ol
                class="carousel-indicators">
                {% for slide in slideshows %}
                    {% if forloop.counter == 1 %}
                    <li data-target="#carousel-1" data-slide-to="0" class="active"></li>
                    {% else %}
                    <li data-target="#carousel-1" data-slide-to={{ forloop.counter0 }}></li>
                    {% endif %}
                {% endfor %}


            </ol>
        </div>
    </section>
    <style>
        div.jumbotron.carousel-hero {
  color: #fff;
  text-align: center;
  background-position: center;
  padding-top: 100px;
  padding-bottom: 100px;
  margin-bottom: 0;
}

h1.hero-title, h2.hero-title, h3.hero-title {
  text-shadow: 0 3px 3px rgba(0,0,0,0.4);
  color: #fff;
}

p.hero-subtitle {
  max-width: 600px;
  margin: 25px auto;
  padding: 10px 15px;
  color: #fff;
}

.plat {
  border-radius: 30px;
}

.btn-primary.focus, .btn-primary:focus {
  box-shadow: 0 0 0 0 #048f83!important;
}

.btn-primary:hover {
  color: #fff;
  background-color: #016090;
  border-color: #016090;
}

.btn.btn-primary {
  background-color: #048f83!important;
  border-color: #048f83!important;
}

.btn-primary.focus, .btn-primary:focus {
  box-shadow: 0 0 0 .2rem rgba(0,123,255,.5);
}

* {
  /*box-sizing: inherit;*/
}

*:before, *:after {
  /*box-sizing: inherit;*/
}

span {
  font-style: inherit;
  font-weight: inherit;
}


    </style>
{% endif %}

templates/navbar.html
{% load static %}
<div style="margin-top: -4px;">
    <nav class="navbar navbar-light navbar-expand-lg bg-light fixed-top" >
        <div class="container" style=""><a class="navbar-brand" href="{% url 'core:home' %}" style="font-family:Arial Narrow, cursive;font-size: 40px;color: #ffffff;"><img src="{% static 'img/logo.png' %}" height="70" width="70"></a>
            <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1" type="button" aria-controls="navcol-1" aria-expanded="false" aria-label="Toggle navigation"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon text-white"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item" role="presentation"><a class="nav-link active bord" href="{% url 'core:home' %}">Home</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link active bord" href="{% url 'core:about' %}">About</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link active bord" href="{% url 'events:events_list' %}">Events</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link active bord" href="{% url 'blog:blog' %}">Blog</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link active bord" href="{% url 'core:contact' %}">Contact</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link active bord" href="{% url 'core:reports' %}" target="_blank">Reports</a></li>  
                    
                    {% if not request.user.is_authenticated %}
                    <li class="nav-item" role="presentation"><a class="nav-link active bord" href="{% url 'accounts:login' %}">Login</a></li>
                    <li class="nav-item border-info hov  text-center border border-danger" role="presentation"><a class="nav-link active" href="{% url 'accounts:register' %}">SignUp</a></li>
                    {% else %}
                    <li class="nav-item" role="presentation"><a class="nav-link active bord" href="{% url 'accounts:dashboard' request.user.username %}">Profile</a></li>
                    <li class="nav-item border-info hov  text-center border border-danger" role="presentation"><a class="nav-link active" href="{% url 'accounts:logout' %}">Logout</a></li>
                    {% endif %}
                    <hr>

                </ul>
            </div>
        </div>
    </nav>
</div>




<style>

     .hov:hover{
        background: rgb(2,0,36);
background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(255,10,151,1) 0%, rgba(255,0,0,1) 100%);
         color: white;

    }

    .hov{
        border-radius: 30px;
    }
    li{
        padding-right: 5px;
        padding-left: 5px;
    }



    li {
    margin-bottom: 4px;
}


.bord::after {
    content: '';
    display: block;
    width: 0;
    height: 2px;
    background: #D9534F;
    transition: width .3s;
}

.bord:hover::after {
    width: 100%;

}
    .nav-item{
        text-transform: capitalize;
        letter-spacing: .1px;
    }


</style>

templates/upcoming_events_card.html
{% if upcomingevents%}
<center><div class="article-list" style="background: rgb(2,0,36); padding-bottom: 20px;
background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(255,10,151,1) 0%, rgba(255,0,0,1) 100%);">
        <div class="container">
            <!-- Start: Intro -->
            <div class="intro" style="padding-top: 30px; margin-bottom: 50px; color: ghostwhite">
                <h1 class="text-center">Upcoming Events</h1>
            </div>
            <!-- End: Intro -->
            <!-- Start: Articles -->
            <div class="row articles wow slideInLeft">

                {% for event in upcomingevents %}
                <a href="{% url 'events:events_detail' event.id%}" style="display: block; text-decoration: none; color:black;">
                    <div class="col-sm-6 col-md-4 item zoom">
                        <div class="card border-white border rounded shadow-lg" style="width: auto; height: 27rem;">
                            <img class="card-img-top" src="{{ event.pic1.url }}" alt="Card image cap" height="200px">
                            <div class="card-body">
                                <center><h5 class="card-title">{{ event.event_name }}</h5></center>
                            <p class="card-text">
                                Date - {{ event.date|date:"d F Y" }}
                                <br>
                                {{ event.description|truncatechars:105 }}
                                <br>
                                <br>
                            </p>
                                <center><a href="{% url 'events:events_detail' event.id%}" class="btn btn-primary action rounded-circle"><i class="fa fa-arrow-right"></i></a></center>
                        </div>
                    </div>
                </a>
            </div>
                {% endfor %}

            <!-- End: Articles -->
            </div>
    </div>
    </div></center>
<style>
    .item{
        margin-bottom: 20px;
    }
    .zoom{
        transition: transform .2s;
    }
    .zoom:hover {

  transform: scale(1.05);
}

</style>
{% endif %}