blog/urls.py
from django.urls import path,include
from . import views


app_name = 'blog'


urlpatterns = [
    path('', views.blog, name='blog'),
    path('<postid>/', views.detail, name='detail'),
    path('<postid>/<commentid>/', views.CommentDelete, name='comment_delete')
]

cncweb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, \
    PasswordResetConfirmView, PasswordChangeView, PasswordChangeDoneView
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from blog.models import Post
from events.models import Event
from events.models import Event
from accounts.models import UserProfile, FacultyProfile
import blog.views
from rest_framework.authtoken import views
from blog.sitemaps import StaticViewSitemap
from core import views as coreviews

sitemaps = {
    'static': StaticViewSitemap,

    'blog': GenericSitemap({
        'queryset': Post.objects.all(),
        'date_field': 'date',
    }, priority=0.7),

    'event': GenericSitemap({
        'queryset': Event.objects.all(),
        'date_field': 'date',
    }, priority=0.8),

    'students': GenericSitemap({
        'queryset': UserProfile.objects.all(),
    }, priority=0.5),

    'teachers': GenericSitemap({
        'queryset': FacultyProfile.objects.all(),
    }, priority=0.6),

}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),

    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('change_password/', PasswordChangeView.as_view(), name='change_password'),
    path('password_change_done/', PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('events/', include('events.urls', namespace='events')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

    path('api-token-auth/', views.obtain_auth_token),
    path('api-auth/', include('rest_framework.urls')),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots\.txt', include('robots.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

]

handler404 = 'core.views.handler404'
handler500 = 'core.views.handler500'
handler403 = 'core.views.handler403'
handler400 = 'core.views.handler400'


# if settings.DEBUG==True:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models
from accounts.models import User, UserProfile
from django.shortcuts import get_object_or_404

member_description = (
    ('Student Co-ordinator', '1-Student Co-ordinator'),
    ('Member', '2-Member'),
    ('Ex Student Co-ordinator', '3-Ex Student Co-ordinator'),
    ('Ex Member', '4-Ex Member')
)

member_status = (
    ('Current', 'Current'),
    ('Alumni', 'Alumni'),
)


class SlideShowPic(models.Model):
    title = models.CharField(max_length=50, default=None, blank=True, null=True)
    image = models.ImageField(default=None, upload_to='slide show pics')
    description = models.CharField(max_length=300, blank=True, null=True)
    url = models.URLField(name='url')
    number = models.IntegerField(default=1, blank=True, null=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['number']


class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    userprofile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, default=None, blank=True, null=True)
    description = models.CharField(choices=member_description, max_length=100)
    status = models.CharField(choices=member_status, max_length=100, blank=True, null=True)

    def __str__(self):
        return str(self.user.username)

    def get_user_profile(self, user):
        userprofile1 = get_object_or_404(UserProfile, user=user)
        return userprofile1

    def save(self, *args, **kwargs):
        userprofile1 = self.get_user_profile(self.user)
        self.userprofile = userprofile1
        super().save(*args, **kwargs)  # call the actual save method

    class Meta:
        ordering = ['-description']


class ContactUs(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(default=None)
    phoneno = models.BigIntegerField(default=None)
    query = models.TextField(max_length=5000)

    def __str__(self):
        return str(self.name)


class Auditions(models.Model):
    name = models.CharField(max_length=1000)
    email = models.EmailField()
    phone = models.BigIntegerField()
    roll_no = models.BigIntegerField(blank=True, null=True)
    hobbies = models.TextField()
    skills = models.CharField(max_length=1000)
    course = models.CharField(max_length=1000)
    branch = models.CharField(max_length=1000)
    reason = models.TextField()
    ip = models.CharField(max_length=1000, default="NA", blank=True, null=True)
    browser = models.CharField(max_length=1000, default="NA", blank=True, null=True)

    def __str__(self):
        return str(self.name) + str(self.roll_no)

templates/auditions/auditions2020.html
{% extends 'base.html'%}
{% load static %}
{% block static %}
    <!-- Primary Meta Tags -->
    <title>Career and Counseling Cell | JC Bose University Faridabad</title>
    <meta name="title" content="Career and Counseling Cell, JC Bose University Faridabad">
    <meta name="description" content="Career and Counseling helps student to achieve excellence in their respective fields and oraganizes seminars in JC BOSE University, YMCA, Faridabad">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://www.cncjcbust.tech/">
    <meta property="og:title" content="Career and Counseling Cell, JC Bose University Faridabad">
    <meta property="og:description" content="Career and Counseling helps student to achieve excellence in their respective fields and oraganizes seminars in JC BOSE University, YMCA, Faridabad">
    <meta property="og:image" content="https://www.cncjcbust.tech/static/img/logo.227277181681.png">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="https://www.cncjcbust.tech/">
    <meta property="twitter:title" content="Career and Counseling Cell, JC Bose University Faridabad">
    <meta property="twitter:description" content="Career and Counseling helps student to achieve excellence in their respective fields and oraganizes seminars in JC BOSE University, YMCA, Faridabad">
    <meta property="twitter:image" content="https://www.cncjcbust.tech/static/img/logo.227277181681.png">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/pace.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/themes/red/pace-theme-flash.min.css">


{% endblock %}




{% block content %}
<br>
<br>
<br>
<br>
<div style="background: rgb(2,0,36);
background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(255,10,151,1) 0%, rgba(255,0,0,1) 100%); padding: 20px; padding-top: 40px">
    <div class="container card wow slideInUp" style=" border-radius: 1%">
        <!-- Start: Contact Form v2 (Modal & Full) with Google Map -->
        <div style="margin-bottom: 110px">
            <!-- Start: Full Page Form -->
            <div class="container-fluid">
                <h1 class="text-center" style="margin-top: 40px;margin-bottom: 40px;">Auditions 2020</h1>
                <hr>
                <form id="registationForm" method="POST">

                    {% csrf_token %}
                    {{ form.errors }}
                    <div class="form-row">
                        <div class="col-md-6">
                            <div id="successfail"></div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-12 col-md-6" id="message">
                            <h2 class="h4"> Registration Form<small><small class="required-input">&nbsp;&nbsp;&nbsp;(*required)</small></small>
                            </h2>
                            <br>
                            <div class="form-group"><label for="id_name">Name</label><span class="required-input">*</span>
                                <div class="input-group">
                                    <div class="input-group-prepend"><span class="input-group-text"><i class="fa fa-user-o"></i></span></div><input class="form-control" type="text" id="id_name" name="name" required="" placeholder="Full Name" maxlength="50"></div>
                            </div>
                            <div class="form-group"><label for="id_email">Email</label><span class="required-input">*</span>
                                <div class="input-group">
                                    <div class="input-group-prepend"><span class="input-group-text"><i class="fa fa-envelope-o"></i></span></div><input class="form-control" type="email" id="id_email" name="email" required="" placeholder="Email Address" maxlength="254"></div>
                            </div>
                            <div class="form-group"><label for="id_phoneno">Roll Number</label>
                                <div class="input-group">
                                    <div class="input-group-prepend"><span class="input-group-text"><i class="fa fa-id-card"></i></span></div><input class="form-control" type="number" id="id_rollno" name="rollno" placeholder="Roll Number" min="18000000000" max="21000000000"></div>
                            </div>
                            <div class="form-group"><label for="id_phoneno">Whatsapp Number</label><span class="required-input">*</span>
                                <div class="input-group">
                                    <div class="input-group-prepend"><span class="input-group-text"><i class="fa fa-phone"></i></span></div><input class="form-control" type="number" id="id_phoneno" name="phoneno" required="" placeholder="Primary Phone" min="6000000000" max="9999999999"></div>
                            </div>
                            <div class="form-group"><label for="id_hobby">Hobbies</label><span class="required-input">*</span>
                                <div class="input-group">
                                    <div class="input-group-prepend"><span class="input-group-text"><i class="fa fa-trophy"></i></span></div><input class="form-control" type="text" id="id_hobby" name="hobbies" required="" placeholder="Your Hobbies" maxlength="200"></div>
                            </div>
                            <div class="form-group">
                                <label for="id_course">Skills:</label><span class="required-input">*</span>
                                <div class="input-group">
                                    <div class="input-group-prepend"><span class="input-group-text"><i class="fa fa-trophy"></i></span>
                                        <select class="form-control" name="skills" id="id_skills">
                                            <option value="Anchoring">Anchoring</option>
                                            <option value="Content">Content Writer</option>
                                            <option value="Marketing">Marketing</option>
                                            <option value="Designing">Designing</option>
                                            <option value="Video">Video Editing</option>
                                            <option value="Others">Others</option>
                                        </select>
                                    </div>
                                </div>
                                
                            </div>
                               <div class="form-group">
                                    <label for="id_course">Course:</label><span class="required-input">*</span>
                                    <div class="input-group">
                                        <div class="input-group-prepend"><span class="input-group-text"><i class="fa fa-university"></i></span>
                                            <select class="form-control" name="course" id="id_course">
                                                <option value="BTECH">B.Tech</option>
                                                <option value="BCA">BCA</option>
                                                <option value="BSC">B.Sc</option>
                                                <option value="BBA">BBA</option>
						                        <option value="MBA">MBA/MA</option>
						                        <option value="Others">Others</option>
                                            </select>
                                        </div>
                                    </div>
                                    
                                </div>
                                <div class="form-group">
                                     <label for="id_course">Branch:</label><span class="required-input">*</span>
                                     <div class="input-group">
                                         <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="fa fa-university"></i></span>
                                            <select class="form-control" name="branch" id="id_branch">
                                                <option value="CEDS">CE (Data Science)</option>
						                        <option value="CE">CE</option>
                                                <option value="IT">IT</option>
                                                <option value="ECE">ECE</option>
                                                <option value="ECS">ECS</option>
                                                <option value="EE">EE (IOT)</option>
                                                <option value="EL">EL</option>
                                                <option value="MECH">MECH</option>
                                                <option value="CIVIL">CIVIL</option>
                                                <option value="Mathematics">Mathematics</option>
                                                <option value="Chemistry">Chemistry</option>
                                                <option value="Physics">Physics</option>
                                                <option value="Animation">Animation</option>
						                        <option value="BCA">Computer Applications</option>
						                        <option value="BAJMC">BAJMC</option>
						                        <option value="MBA">MBA/MA</option>
                                                <option value="Others">Others</option>
                                            </select>
                                         </div>
                                     </div>
                                     
                                 </div>
 
                            <div class="form-group"><label for="id_query">Why you want to join Career and Counselling Cell</label><span class="required-input">*</span><textarea class="form-control" id="id_question" name="reason" placeholder="Answer" rows="5" maxlength="5000"></textarea></div>
                            <div class="form-group">
                                <div class="form-row">
                                    <div class="col"><button class="btn btn-dark border-0 btn-block zoom" style="background: rgb(2,0,36);
background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(255,10,151,1) 0%, rgba(255,0,0,1) 100%); margin: 5px;" type="reset"><i class="fa fa-undo"></i> Reset</button></div>
                                    <div class="col"><button class="btn btn-dark border-0 btn-block zoom" style="background: rgb(2,0,36);
background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(255,10,151,1) 0%, rgba(255,0,0,1) 100%); margin: 5px;" type="submit" value="submit">Submit <i class="fa fa-chevron-circle-right"></i></button></div>
                                </div>
                            </div>
                            <hr class="d-flex d-md-none">
                        </div>
                       </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

  
{% endblock %}
{% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js">

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>


{% endblock %}