accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),

    path('<username>/', views.ProfileDashboard, name='dashboard'),
    # path('<username>/edit_student_profile', views.EditStudentProfileView, name='edit_student_profile'),

]

blog/urls.py
from django.urls import path,include
from . import views


app_name = 'blog'


urlpatterns = [
    path('', views.blog, name='blog'),
    path('<postid>/', views.detail, name='detail'),
    path('<postid>/<commentid>/', views.CommentDelete, name='comment_delete')
]

cncweb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, \
    PasswordResetConfirmView, PasswordChangeView, PasswordChangeDoneView
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from blog.models import Post
from events.models import Event
from events.models import Event
from accounts.models import UserProfile, FacultyProfile
import blog.views
from rest_framework.authtoken import views
from blog.sitemaps import StaticViewSitemap
from core import views as coreviews

sitemaps = {
    'static': StaticViewSitemap,

    'blog': GenericSitemap({
        'queryset': Post.objects.all(),
        'date_field': 'date',
    }, priority=0.7),

    'event': GenericSitemap({
        'queryset': Event.objects.all(),
        'date_field': 'date',
    }, priority=0.8),

    'students': GenericSitemap({
        'queryset': UserProfile.objects.all(),
    }, priority=0.5),

    'teachers': GenericSitemap({
        'queryset': FacultyProfile.objects.all(),
    }, priority=0.6),

}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),

    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('change_password/', PasswordChangeView.as_view(), name='change_password'),
    path('password_change_done/', PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('events/', include('events.urls', namespace='events')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

    path('api-token-auth/', views.obtain_auth_token),
    path('api-auth/', include('rest_framework.urls')),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots\.txt', include('robots.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

]

handler404 = 'core.views.handler404'
handler500 = 'core.views.handler500'
handler403 = 'core.views.handler403'
handler400 = 'core.views.handler400'


# if settings.DEBUG==True:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

events/urls.py
from django.urls import path
from . import views


app_name = 'events'


urlpatterns = [
    path('', views.EventsList, name='events_list'),
    path('<int:eventid>/', views.EventDetail, name='events_detail'),
    path('certi', views.Getpdf, name='certi'),
    path('<username>/<eventid>/', views.Getpdf, name='certificate'),
    path('<eventid>/register', views.RegisterForEvent, name='register_for_event'),
    path('<eventid>/unregister', views.UnregisterForEvent, name='unregister_for_event'),

]

events/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField


class Event(models.Model):
    event_name = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    certi_description = RichTextUploadingField(blank=True, null=True)
    content = RichTextUploadingField(blank=True, null=True)
    date = models.DateTimeField(blank=True, null=True)
    venue = models.CharField(max_length=100, default=None, blank=True, null=True)
    pic1 = models.ImageField(default=None, upload_to='event pics')
    pic2 = models.ImageField(default=None, upload_to='event pics', blank=True, null=True)
    pic3 = models.ImageField(default=None, upload_to='event pics', blank=True, null=True)
    pic4 = models.ImageField(default=None, upload_to='event pics', blank=True, null=True)
    pic5 = models.ImageField(default=None, upload_to='event pics', blank=True, null=True)
    pic6 = models.ImageField(default=None, upload_to='event pics', blank=True, null=True)
    pic7 = models.ImageField(default=None, upload_to='event pics', blank=True, null=True)
    pic8 = models.ImageField(default=None, upload_to='event pics', blank=True, null=True)
    pic9 = models.ImageField(default=None, upload_to='event pics', blank=True, null=True)
    pic10 = models.ImageField(default=None, upload_to='event pics', blank=True, null=True)
    pic11 = models.ImageField(default=None, upload_to='event pics', blank=True, null=True) ##for home only
    status = models.CharField(default=True, choices=(('True', 'Upcoming'), ('False', 'Happened')), max_length=10)

    def __str__(self):
        return self.event_name

    def get_absolute_url(self):
        return reverse('events:events_detail', args=[str(self.pk)])

    class Meta:
        ordering = ['-date']


class Registration(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='registrations')
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    attended = models.CharField(choices=(('A', 'Attended'), ('NA', 'Not Attended')), max_length=10, default='NA')

    def __str__(self):
        return self.event.event_name + self.user.username

    def is_user_registered_for_event(self, user, event):
        if self.objects.get(user=user, event=event):
            return True
        else:
            return False

    class Meta:
        ordering = ['-date']


class Institute(models.Model):
    institute = models.CharField(max_length=100)
    previous_events = RichTextUploadingField(blank=True, null=True)
    contact_person = models.CharField(max_length=1000, blank=True, null=True)
    contact_person_phone_number = models.BigIntegerField(blank=True, null=True)
    email = models.EmailField(max_length=100, default=None, blank=True, null=True)

    def __str__(self):
        return self.institute

    class Meta:
        ordering = ['institute']

events/forms.py
from django import forms
from django.core.exceptions import ValidationError


class SuggestEvent(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    first_name = forms.CharField(label='First Name', max_length=50)
    last_name = forms.CharField(label='Last Name', max_length=50)
    email = forms.EmailField(label='Email ID')

    password1 = forms.CharField(label='Password', min_length=6,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Confirm Password', min_length=6,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    roll_no = forms.IntegerField(label='Roll No.', min_value=10000000000, max_value=100000000000)
    course = forms.ChoiceField(label='Course', choices=course)
    branch = forms.ChoiceField(label='Branch', choices=branch)
    phoneno = forms.IntegerField(label='Phone No.', min_value=6000000000, max_value=9999999999)

events/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import Event, Registration
from accounts.models import UserProfile
from .certificates import render_to_pdf, render_pdf_view
from django.contrib.auth.models import User
import datetime
from django.contrib import messages
from django.core.paginator import Paginator
import urllib.request


# Create your views here.


def EventsList(request):
    events = Event.objects.filter(status='False').order_by('-date')
    get_dict_copy = request.GET.copy()

    search_term = ''
    if 'month' and 'year' and 'search' in request.GET:
        m = request.GET['month']
        y = request.GET['year']
        search_term = request.GET['search']

        if m == '' and y == '':
            events = Event.objects.filter(status='False',event_name__icontains=search_term).order_by('-date')
        elif m == '':
            y = int(y)
            events = Event.objects.filter(status='False', date__year=y, event_name__icontains=search_term).order_by('-date')
        elif y=='':
            m = int(m)
            events = Event.objects.filter(status='False', date__month=m, event_name__icontains=search_term).order_by('-date')

        else:
            m = int(m)
            y = int(y)
            events = Event.objects.filter(status='False', date__gte=datetime.date(y, m, 1), date__lt=datetime.date(y, m+1, 1), event_name__icontains=search_term).order_by('-date')

    elif 'search' in request.GET:
        search_term = request.GET['search']
        events = Event.objects.filter(status='False', event_name__icontains=search_term).order_by('-date')

    paginator_event = Paginator(events, 10)
    page = request.GET.get('page')
    events = paginator_event.get_page(page)

    params = get_dict_copy.pop('page', True) and get_dict_copy.urlencode()
    context = {
        'allevents': paginator_event,
        'events': events,
        'params': params,
        'search_term': search_term,
    }
    return render(request, 'events/event_list.html', context)


def EventDetail(request, eventid):
    event = get_object_or_404(Event, id=eventid)
    user = request.user
    try:
        registration = Registration.objects.get(user=user, event=event)
    except:
        registration = None

    context = {
        'event': event,
        'registration': registration
    }
    return render(request, 'events/event_detail1.html', context)


def Getpdf(request, username, eventid, *args, **kwargs):
    user = get_object_or_404(User, username=username)
    event = get_object_or_404(Event, id=eventid)
    userprofile = get_object_or_404(UserProfile, user=user)
    if username == user.username:
        data = {
            'user': user,
            'event': event,
            'userprofile': userprofile,
        }
        return render(request, 'events/certi.html', data)
        # pdf = render_pdf_view(request, 'events/certi.html', data)
        # return HttpResponse(pdf, content_type='application/pdf')
    else:
        return HttpResponse('404')


@login_required
def RegisterForEvent(request, eventid):
    user = request.user
    event = get_object_or_404(Event, id=eventid)
    registration = Registration.objects.get_or_create(user=user, event=event)
    messages.success(request, 'Thanks for registering for Event - {}'.format(event.event_name))
    return redirect('events:events_detail', eventid=event.id)


@login_required
def UnregisterForEvent(request, eventid):
    user = request.user
    event = get_object_or_404(Event, id=eventid)
    registration = get_object_or_404(Registration, user=user, event=event)
    registration.delete()
    messages.error(request, 'You\'ve Unregistered for Event - {}'.format(event.event_name))
    return redirect('events:events_detail', eventid=event.id)

templates/events/certi1.html
{% load static %}
<html>
<head>
<meta charset="UTF-8">
    <title>
        Certificate
    </title>


<!--    <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet" />-->
<style>
        @page{
        size: a4 landscape;
        padding: 10pt;
        @frame header_frame {
        -pdf-frame-content: header_content;
        top: 260pt;
        }
        @frame description_frame {
        -pdf-frame-content: description_content;
        top: 350pt;
        margin-left: 130pt;
        margin-right: 130pt;
        }

        @frame signature1_frame {
        -pdf-frame-content: signature1_content;
        top: 500pt;
        left: 203pt;
        }

        @frame signature1_frame {
        -pdf-frame-content: signature2_content;
        top: 500pt;
        left: 533pt;

        }
    }
</style>
</head>

<body style="background-image: url('https://cncymca.s3.us-east-2.amazonaws.com/3401082.jpg')">
    <div>
        <img src="https://cncymca.s3.us-east-2.amazonaws.com/3401082.jpg"/>
        <div id="header_content">
            <h1 style="font-size: 74px; text-align: center;">{{ user.first_name }} {{ user.last_name }}</h1>
        </div>
        <div id="description_content">
            <h5 style="font-size: 20px; text-align: center; color: grey;">{{ event.certi_description }}
            </h5>
        </div>
        <div id="signature1_content">
            <h3 style="font-size: 16px;">Nitesh Sharma</h3>
        </div>
        <div id="signature2_content">
            <h3 style="font-size: 16px;">Sanyam Mittal</h3>
        </div>

    </div>
</body>
</html>

templates/events/event_detail1.html
{% extends 'base.html' %}
{% load static %}
{% block static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">

    <title>{{ event.event_name|title }} | Career and Counseling Cell | JC Bose UST</title>
    <meta name="title" content="{{ event.event_name|title }} | Career and Counseling Cell | JC Bose UST">
    <meta name="description" content="{{ event.description|safe|truncatechars:150 }}">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://www.cncjcbust.tech/events/{{ event.id }}/">
    <meta property="og:title" content="{{ event.event_name|title }} | Career and Counseling Cell | JC Bose UST">
    <meta property="og:description" content="{{ event.description|safe|truncatechars:150 }}">
    {% if event.pic1.url %}
    <meta property="og:image" content="{{event.pic1.url}}">
    {% endif %}

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="https://www.cncjcbust.tech/events/{{ event.id }}/">
    <meta property="twitter:title" content="{{ event.event_name|title }} | Career and Counseling Cell | JC Bose UST">
    <meta property="twitter:description" content="{{ event.description|safe|truncatechars:150 }}">
    {% if event.pic1.url %}
    <meta property="og:image" content="{{event.pic1.url}}">
    {% endif %}

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=ABeeZee">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli">
{% endblock %}



{% block content %}
<br>
<br>
<br>
<div style="background: rgb(2,0,36);
background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(255,10,151,1) 0%, rgba(255,0,0,1) 100%); padding: 20px;">
    <div class="article-dual-column">
        <div class="container card blog-content border-grey border rounded shadow-lg">




                    <div class="intro">
                        <h2 class="text-center">{{ event.event_name|title }}</h2>
                        <p class="text-center">
                            <h6>Event Date - {{ event.date|date:'d F Y'}} </h6>
                        </p>
                        <hr>
                        <p class="text-dark text-center">{{ event.description|capfirst|safe }}</p>

                        {% if event.pic2 %}
                        <center><img class="img-fluid" src="{{ event.pic2.url }}" style="height: 300px;"></center><br>
                        {% endif %}

                    </div>

                    <div class="text container">
                        <p>
                            {{ event.content|safe }}
                        </p>
                        <br>
                        {% if event.pic1 %}
                        <figure class="figure">
                            <img class="figure-img" src="{{event.pic1.url}}" alt="" height="200px">
                        </figure>
                        {% endif %}
                    </div>
                    <br>
            <br>
            <div class="container mb-4">
                <div class="d-flex justify-content-center">
                        <div class="row">
                        {% if event.pic3 %}
                        <img class="col-sm-6 col-md-4  img-fluid mt-3 mb-3" src="{{event.pic3.url}}" alt="Event Image Career and Counselling Cell" />
                        {% endif %}

                    {% if event.pic4 %}
                        <img class="col-sm-6 col-md-4  img-fluid mt-3 mb-3" src="{{event.pic4.url}}" alt="Event Image Career and Counselling Cell" />
                        {% endif %}

                    {% if event.pic5 %}
                        <img class="col-sm-6 col-md-4  img-fluid mt-3 mb-3" src="{{event.pic5.url}}" alt="Event Image Career and Counselling Cell" />
                        {% endif %}

                    {% if event.pic6 %}
                        <img class="col-sm-6 col-md-4  img-fluid mt-3 mb-3" src="{{event.pic6.url}}" alt="Event Image Career and Counselling Cell" />
                        {% endif %}

                    {% if event.pic7 %}
                        <img class="col-sm-6 col-md-4  img-fluid mt-3 mb-3" src="{{event.pic7.url}}" alt="Event Image Career and Counselling Cell" />
                        {% endif %}
                    {% if event.pic8 %}
                        <img class="col-sm-6 col-md-4  img-fluid mt-3 mb-3" src="{{event.pic8.url}}" alt="Event Image Career and Counselling Cell" />
                        {% endif %}
                    {% if event.pic9 %}
                        <img class="col-sm-6 col-md-4  img-fluid mt-3 mb-3" src="{{event.pic9.url}}" alt="Event Image Career and Counselling Cell" />
                        {% endif %}
                    {% if event.pic10 %}
                        <img class="col-sm-6 col-md-4  img-fluid mt-3 mb-3" src="{{event.pic10.url}}" alt="Event Image Career and Counselling Cell" />
                        {% endif %}
                    {% if event.pic11 %}
                        <img class="col-sm-6 col-md-4  img-fluid mt-3 mb-3" src="{{event.pic3.url}}" alt="Event Image Career and Counselling Cell" />
                        {% endif %}
                        </div>

                </div>
            </div>
            <div style="align-self: center; padding-bottom: 20px">
                {% if event.status == 'True' %}
                    {% if registration %}
                        <div class="row" style="align-self: center">
                            <a class="text-sm-center text-white det btn" style="background: rgb(2,0,36);
    background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(255,10,151,1) 0%, rgba(255,0,0,1) 100%)" href="{% url 'events:unregister_for_event' event.id%}">Unregister</a></center>
                        </div>
                    {% else %}
                        <div class="row" style="align-self: center">
                            <a class="text-sm-center text-white det btn" style="background: rgb(2,0,36);
    background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(255,10,151,1) 0%, rgba(255,0,0,1) 100%)" href="{% url 'events:register_for_event' event.id%}">Register</a></center>
                        </div>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>




        <!-- GALLERY -->



    <style>
        .blog-content{
        text-align: center;
        margin-top: 30px;
    }
    .text{
        text-align: left;
    }

    </style>
{% endblock %}



    {% block scripts %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.2/dist/jquery.fancybox.min.js"></script>
    {% endblock %}

templates/events/events_timeline.html
{% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    {% block static %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=ABeeZee">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli">

    {% endblock %}
<div class="wow slideInUp" style="padding: 20px; padding-top: 50px; margin-top: 10px">
    <section class="index-howto-alt">






        <div class=" wow slideInUp row justify-content-center">
      <!-- Column -->
      <div class="col-md-12 text-center mb-3">
        <h2 class="my-1">EVENTS SO FAR</h2>
      </div>
    </div>
        <div class="wow slideInUp row" style="justify-content: center;">
        <form class="form-inline">

        <div class="col-md-3">
            <div class="form-group">
                <select style="border-radius: 10px;" class="form-control" name="month" id="id_month">
                    <option value="">Select Month</option>
                    <option value="01">January</option>
                    <option value="02">February</option>
                    <option value="03">March</option>
                    <option value="04">April</option>
                    <option value="05">May</option>
                    <option value="06">June</option>
                    <option value="07">July</option>
                    <option value="08">August</option>
                    <option value="09">September</option>
                    <option value="10">October</option>
                    <option value="11">November</option>
                    <option value="12">December</option>
                </select>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                <select style="border-radius: 10px;" class="form-control" name="year" id="id_course">
                    <option value="">Select Year</option>
                    <option value="2020">2020</option>
                    <option value="2019">2019</option>
                    <option value="2018">2018</option>
                    <option value="2017">2017</option>

                </select>
            </div>
        </div>
            <div class="col-md-4">
                <input
                class="form-control"
                type="search"
                placeholder="Search by Event Name"
                aria-label="Search"
                name='search'
                value="{{search_term}}">

            </div>

            <div class="col-md-2">
        <button class="btn btn-danger  my-2 my-sm-0" type="submit">Search</button>
            </div>
        </form>
        </div>

    </div>
        </div>
<hr>


<!--          <form class="form-inline my-2 my-lg-1" action="?{{ params }}&">-->
<!--            <input-->
<!--                class="form-control mr-sm-2"-->
<!--                type="search"-->
<!--                placeholder="Search by Event Name"-->
<!--                aria-label="Search"-->
<!--                name='search'-->
<!--                value="{{search_term}}">-->
<!--            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--          </form>-->



<div class="bg-white p-0">
<div class="container mt-3">
        {% for event in events %}
                {% if event.status == 'False' %}
        {% if forloop.counter0|divisibleby:"2" %}
            <div class="row wow slideInLeft flex-column-reverse align-items-center flex-sm-row">
                    <div class="card border-white border rounded shadow-lg col-12 col-sm-6 d-flex flex-column justify-content-center p-5 psd-right1">
                        <center><h3 class="text-sm-center">{{ event.event_name|capfirst|truncatechars:50 }}</h3>
                        <h6 class="text-sm-center">{{ event.date }}</h6>
                            <h6 class="text-sm-center">{{ event.venue }}</h6>
                        <p class="text-sm-center">{{ event.description|truncatechars:60 }}<br></p>
                        <a class="text-sm-center text-white det btn" style="background: rgb(2,0,36);
background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(255,10,151,1) 0%, rgba(255,0,0,1) 100%)" href="{% url 'events:events_detail' event.id %}" >Event Details</a></center>
                    </div>

                    <div class="col-12 col-sm-6 d-flex flex-row justify-content-center align-items-center intro-card-2 p-5">
                        <img class="howto-img imground" src="{{ event.pic2.url }}" alt="{{ event.event_name|capfirst|truncatechars:50 }}" href="{% url 'events:events_detail' event.id %}" width="200" height="200">
                    </div>
                </div>
        {% elif not forloop.counter0|divisibleby:"2"%}
            <div class="row wow slideInRight align-items-center">
                    <div class="col-12 col-sm-6 d-flex flex-row justify-content-center align-items-center intro-card-3 p-5">
                        <img class="howto-img imground" src="{{ event.pic2.url }}" href="{% url 'events:events_detail' event.id %}" alt="{{ event.event_name|capfirst|truncatechars:50 }}" width="200" height="200">
                    </div>
                    <div class="card border-white border rounded shadow-lg col-12 col-sm-6 d-flex flex-column justify-content-center p-5 psd-left2">
                        <center><h3 class="text-sm-center">{{ event.event_name|capfirst|truncatechars:50 }}</h3>
                        <h6 class="text-sm-center">{{ event.date }}</h6>
                        <p class="text-sm-center">{{ event.description|truncatechars:60 }}<br></p>
                        <a class="text-sm-center text-white det btn" style="background: rgb(2,0,36);
background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(255,10,151,1) 0%, rgba(255,0,0,1) 100%)" href="{% url 'events:events_detail' event.id %}">Event Details</a></center></div>
                    </div>
        {% endif %}
    {% endif %}
     {% endfor %}
</div>
</div>
            </div>

        </div>
    </section>

    <div class="pagination container" style="padding: 50px">
            <span class="step-links">
            {% if events.has_previous %}
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a href="?page=1&{{params}}" style="padding-right: 3px;"><button type="button" class="btn btn-secondary">&laquo; First</button></a>
                    <a href="?page={{ events.previous_page_number }}&{{params}}"><button type="button" class="btn btn-secondary">Previous</button></a>
                </div>
            {% endif %}

                <div class="btn-group" role="group" aria-label="Basic example">

            {% for i in allevents.page_range %}
            {% if i > events.number|add:'-3' and i < events.number|add:'3' %}

                    <a href="?page={{ i }}&{{params}}" style="padding-right: 3px;"><button type="button" class="btn btn-secondary">{{ i }}</button></a>

            {% endif %}
            {% endfor %}
                    </div>

            {% if events.has_next %}
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a href="?page={{ events.next_page_number }}&{{params}}" style="padding-right: 3px;"><button type="button" class="btn btn-secondary">Next</button></a>
                    <a href="?page={{ events.paginator.num_pages }}&{{params}}"><button type="button" class="btn btn-secondary">Last &raquo;</button></a>
                </div>
            {% endif %}
            </span>
        </div>


</div>
<style>
    .imground{
        border: 8px solid red;
        border-radius: 100%;
    }
    .det:hover{
        display: block;
        text-decoration: none;
    }
    .det{
        width: 10rem;
    }
</style>

    {% block scripts %}
    <script src="{% static 'js/jquery.min.js'%}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js'%}"></script>
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.2/dist/jquery.fancybox.min.js"></script>
    {% endblock %}

templates/events/profile_sidebar.html
{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static 'css/LinkedIn-like-Profile-Box.css' %}">
{% endblock %}


{% if request.user.is_authenticated %}
    <div class="col-xl-3 offset-xl-0">
        <div class="row"></div>
        <div class="text-center border rounded-0 shadow-sm profile-box" style="width: 200px;height: 300px;background-color: #ffffff;margin: 5px;">
            <div style="height: 50px;background-image: url({% static 'img/bg-pattern.png' %});background-color: rgba(54,162,177,0);"></div>
            <div>
                <img class="rounded-circle" src="{{ request.user.userprofile.pic.url }}" width="60px" height="60px" style="background-color: rgb(255,255,255);padding: 2px;">
            </div>
            <div style="height: 100px;">
                <h4>{{ request.user.first_name|capfirst }} {{ request.user.last_name|capfirst }}</h4>
                <p style="font-size: 14px;">{{ request.user.userprofile.roll_no|upper }}</p>
                <p style="font-size: 12px;">{{ request.user.userprofile.course|upper }} {{ request.user.userprofile.branch|upper }}</p>
            </div>
            <div style="height: 80px;">
                <p>{{ request.user.email }}</p>
                <p>{{ request.user.userprofile.phoneno }}</p>
            </div>

            <a href="{% url 'accounts:dashboard' request.user.username %}">View Profile</a>
        </div>
    </div>
{% endif %}